// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSXJOFsG6SxYFBv375AUtoaAVY4VkXWgo',
    appId: '1:818491472446:web:29a274a98b0eef62096f6f',
    messagingSenderId: '818491472446',
    projectId: 'snipscholar-c39f8',
    authDomain: 'snipscholar-c39f8.firebaseapp.com',
    storageBucket: 'snipscholar-c39f8.firebasestorage.app',
    measurementId: 'G-J0JTVPVM9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3yTVRUAgwmMb3Xt6Hdfq70O-7XtuHz5M',
    appId: '1:818491472446:android:e5d82f8c7b55e8f0096f6f',
    messagingSenderId: '818491472446',
    projectId: 'snipscholar-c39f8',
    storageBucket: 'snipscholar-c39f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQh7o_smyOPnywkRktOl7UlmDl0hUoK_w',
    appId: '1:818491472446:ios:5f198cde90205c1e096f6f',
    messagingSenderId: '818491472446',
    projectId: 'snipscholar-c39f8',
    storageBucket: 'snipscholar-c39f8.firebasestorage.app',
    iosBundleId: 'com.example.snipscholar',
  );
}
